services:
  siga-db:
    image: postgres:16
    container_name: siga-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: siga
      POSTGRES_USER: siga_user
      POSTGRES_PASSWORD: siga_password
    ports:
      - "5434:5432"
    volumes:
      - siga_pgdata:/var/lib/postgresql/data

volumes:
  siga_pgdata:
