// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIGA.Infrastructure.Persistence;

#nullable disable

namespace SIGA.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SigaDbContext))]
    [Migration("20260918010316_AgregarIndicesUnicosDispositivoYEmail")]
    partial class AgregarIndicesUnicosDispositivoYEmail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SIGA.Domain.Entities.CaptacionGanado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("EstadoSanitario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EstadoSync")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("EstanciaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacionLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaSincronizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("ModificadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Potrero")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.HasIndex("EstanciaId");

                    b.HasIndex("ModificadoPorUsuarioId");

                    b.ToTable("CaptacionesGanado", null, t =>
                        {
                            t.HasCheckConstraint("CK_CaptacionesGanado_Latitud", "\"Latitud\" IS NULL OR \"Latitud\" BETWEEN -90 AND 90");

                            t.HasCheckConstraint("CK_CaptacionesGanado_Longitud", "\"Longitud\" IS NULL OR \"Longitud\" BETWEEN -180 AND 180");
                        });
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Departamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Departamentos", (string)null);
                });

            modelBuilder.Entity("SIGA.Domain.Entities.DetalleLoteGanado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ActualizadoPor")
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadCabezas")
                        .HasColumnType("integer");

                    b.Property<Guid>("CaptacionGanadoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreadoPor")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FechaEstimadaFaena")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotasZootecnicas")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<double?>("PesoPromedioEstimadoKg")
                        .HasColumnType("double precision");

                    b.Property<string>("Raza")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("RazaId")
                        .HasColumnType("uuid");

                    b.Property<string>("SistemaAlimentacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ActualizadoPor");

                    b.HasIndex("CaptacionGanadoId");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("RazaId");

                    b.ToTable("DetallesLoteGanado", null, t =>
                        {
                            t.HasCheckConstraint("CK_DetallesLoteGanado_CantidadCabezas", "\"CantidadCabezas\" > 0");

                            t.HasCheckConstraint("CK_DetallesLoteGanado_PesoPromedioEstimadoKg", "\"PesoPromedioEstimadoKg\" IS NULL OR \"PesoPromedioEstimadoKg\" > 0");
                        });
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Dispositivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("IdentificadorDispositivo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("UbicacionActual")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UltimaSincronizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdentificadorDispositivo")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("Dispositivos", (string)null);
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Estancia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaptadorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("DepartamentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("EstadoSync")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaCreacionLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaSincronizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("HectareasTotales")
                        .HasColumnType("double precision");

                    b.Property<double>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("ModificadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Municipio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("MunicipioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Propietario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ProvinciaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Renspa")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Representante")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CaptadorId");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("ModificadoPorUsuarioId");

                    b.HasIndex("MunicipioId");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Estancias", null, t =>
                        {
                            t.HasCheckConstraint("CK_Estancias_HectareasTotales", "\"HectareasTotales\" IS NULL OR \"HectareasTotales\" > 0");

                            t.HasCheckConstraint("CK_Estancias_Latitud", "\"Latitud\" BETWEEN -90 AND 90");

                            t.HasCheckConstraint("CK_Estancias_Longitud", "\"Longitud\" BETWEEN -180 AND 180");
                        });
                });

            modelBuilder.Entity("SIGA.Domain.Entities.LogAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Detalle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdRegistroAfectado")
                        .HasColumnType("uuid");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FechaHora");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogsAuditoria", (string)null);
                });

            modelBuilder.Entity("SIGA.Domain.Entities.MovimientoGanado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadCabezas")
                        .HasColumnType("integer");

                    b.Property<Guid>("CaptacionGanadoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("EstadoSync")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacionLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaSincronizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModificadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("TipoGanado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CaptacionGanadoId");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.HasIndex("ModificadoPorUsuarioId");

                    b.ToTable("MovimientosGanado", null, t =>
                        {
                            t.HasCheckConstraint("CK_MovimientosGanado_CantidadCabezas", "\"CantidadCabezas\" > 0");
                        });
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Municipio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProvinciaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId", "Nombre")
                        .IsUnique();

                    b.ToTable("Municipios", (string)null);
                });

            modelBuilder.Entity("SIGA.Domain.Entities.PermisoUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("TipoPermiso")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PermisosUsuario", (string)null);
                });

            modelBuilder.Entity("SIGA.Domain.Entities.ProductoTratamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("ProductosTratamiento", (string)null);
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Provincia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartamentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId", "Nombre")
                        .IsUnique();

                    b.ToTable("Provincias", (string)null);
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Raza", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Razas", (string)null);
                });

            modelBuilder.Entity("SIGA.Domain.Entities.RegistroAlimentacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaptacionGanadoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("EstadoSync")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacionLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaSincronizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModificadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<double?>("RacionBaseKgAnimal")
                        .HasColumnType("double precision");

                    b.Property<double?>("SuplementoProteicoKgAnimal")
                        .HasColumnType("double precision");

                    b.Property<string>("TipoAlimentacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CaptacionGanadoId");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.HasIndex("ModificadoPorUsuarioId");

                    b.ToTable("RegistrosAlimentacion", null, t =>
                        {
                            t.HasCheckConstraint("CK_RegistrosAlimentacion_RacionBaseKgAnimal", "\"RacionBaseKgAnimal\" IS NULL OR \"RacionBaseKgAnimal\" >= 0");

                            t.HasCheckConstraint("CK_RegistrosAlimentacion_SuplementoProteicoKgAnimal", "\"SuplementoProteicoKgAnimal\" IS NULL OR \"SuplementoProteicoKgAnimal\" >= 0");
                        });
                });

            modelBuilder.Entity("SIGA.Domain.Entities.RegistroPesaje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CantidadCabezasPesadas")
                        .HasColumnType("integer");

                    b.Property<Guid>("CaptacionGanadoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("EstadoSync")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacionLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaSincronizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModificadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<double>("PesoPromedioKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CaptacionGanadoId");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.HasIndex("ModificadoPorUsuarioId");

                    b.ToTable("RegistrosPesaje", null, t =>
                        {
                            t.HasCheckConstraint("CK_RegistrosPesaje_CantidadCabezasPesadas", "\"CantidadCabezasPesadas\" IS NULL OR \"CantidadCabezasPesadas\" > 0");

                            t.HasCheckConstraint("CK_RegistrosPesaje_PesoPromedioKg", "\"PesoPromedioKg\" > 0");
                        });
                });

            modelBuilder.Entity("SIGA.Domain.Entities.RegistroSanitario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaptacionGanadoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("EstadoSync")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacionLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaSincronizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModificadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ProductoTratamiento")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ProductoTratamientoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegistradoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CaptacionGanadoId");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.HasIndex("ModificadoPorUsuarioId");

                    b.HasIndex("ProductoTratamientoId");

                    b.HasIndex("RegistradoPorUsuarioId");

                    b.ToTable("RegistrosSanitarios", (string)null);
                });

            modelBuilder.Entity("SIGA.Domain.Entities.SectorAsignado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NombreSector")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Zona")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SectoresAsignados", (string)null);
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cargo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasDiscriminator<string>("TipoUsuario").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Administrador", b =>
                {
                    b.HasBaseType("SIGA.Domain.Entities.Usuario");

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Captador", b =>
                {
                    b.HasBaseType("SIGA.Domain.Entities.Usuario");

                    b.HasDiscriminator().HasValue("Captador");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.CaptacionGanado", b =>
                {
                    b.HasOne("SIGA.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGA.Domain.Entities.Estancia", "Estancia")
                        .WithMany("Captaciones")
                        .HasForeignKey("EstanciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGA.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ModificadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Estancia");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.DetalleLoteGanado", b =>
                {
                    b.HasOne("SIGA.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ActualizadoPor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SIGA.Domain.Entities.CaptacionGanado", "CaptacionGanado")
                        .WithMany("Detalles")
                        .HasForeignKey("CaptacionGanadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGA.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGA.Domain.Entities.Raza", "RazaCatalogo")
                        .WithMany()
                        .HasForeignKey("RazaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CaptacionGanado");

                    b.Navigation("RazaCatalogo");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Dispositivo", b =>
                {
                    b.HasOne("SIGA.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Dispositivos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Estancia", b =>
                {
                    b.HasOne("SIGA.Domain.Entities.Captador", "Captador")
                        .WithMany("Estancias")
                        .HasForeignKey("CaptadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGA.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGA.Domain.Entities.Departamento", "DepartamentoCatalogo")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SIGA.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ModificadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SIGA.Domain.Entities.Municipio", "MunicipioCatalogo")
                        .WithMany()
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SIGA.Domain.Entities.Provincia", "ProvinciaCatalogo")
                        .WithMany()
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Captador");

                    b.Navigation("DepartamentoCatalogo");

                    b.Navigation("MunicipioCatalogo");

                    b.Navigation("ProvinciaCatalogo");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.LogAuditoria", b =>
                {
                    b.HasOne("SIGA.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.MovimientoGanado", b =>
                {
                    b.HasOne("SIGA.Domain.Entities.CaptacionGanado", "CaptacionGanado")
                        .WithMany("Movimientos")
                        .HasForeignKey("CaptacionGanadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGA.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGA.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ModificadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CaptacionGanado");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Municipio", b =>
                {
                    b.HasOne("SIGA.Domain.Entities.Provincia", "Provincia")
                        .WithMany("Municipios")
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.PermisoUsuario", b =>
                {
                    b.HasOne("SIGA.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Permisos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Provincia", b =>
                {
                    b.HasOne("SIGA.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Provincias")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.RegistroAlimentacion", b =>
                {
                    b.HasOne("SIGA.Domain.Entities.CaptacionGanado", "CaptacionGanado")
                        .WithMany("RegistrosAlimentacion")
                        .HasForeignKey("CaptacionGanadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGA.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGA.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ModificadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CaptacionGanado");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.RegistroPesaje", b =>
                {
                    b.HasOne("SIGA.Domain.Entities.CaptacionGanado", "CaptacionGanado")
                        .WithMany("RegistrosPesaje")
                        .HasForeignKey("CaptacionGanadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGA.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGA.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ModificadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CaptacionGanado");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.RegistroSanitario", b =>
                {
                    b.HasOne("SIGA.Domain.Entities.CaptacionGanado", "CaptacionGanado")
                        .WithMany("RegistrosSanitarios")
                        .HasForeignKey("CaptacionGanadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGA.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGA.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ModificadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SIGA.Domain.Entities.ProductoTratamiento", "ProductoTratamientoCatalogo")
                        .WithMany()
                        .HasForeignKey("ProductoTratamientoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SIGA.Domain.Entities.Usuario", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CaptacionGanado");

                    b.Navigation("ProductoTratamientoCatalogo");

                    b.Navigation("RegistradoPor");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.SectorAsignado", b =>
                {
                    b.HasOne("SIGA.Domain.Entities.Usuario", "Usuario")
                        .WithMany("SectoresAsignados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.CaptacionGanado", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Movimientos");

                    b.Navigation("RegistrosAlimentacion");

                    b.Navigation("RegistrosPesaje");

                    b.Navigation("RegistrosSanitarios");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Provincias");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Estancia", b =>
                {
                    b.Navigation("Captaciones");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Provincia", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Dispositivos");

                    b.Navigation("Permisos");

                    b.Navigation("SectoresAsignados");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Captador", b =>
                {
                    b.Navigation("Estancias");
                });
#pragma warning restore 612, 618
        }
    }
}
