// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIGA.Infrastructure.Persistence;

#nullable disable

namespace SIGA.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SigaDbContext))]
    partial class SigaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SIGA.Domain.Entities.CaptacionGanado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("EstadoSanitario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EstadoSync")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("EstanciaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacionLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaSincronizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModificadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Potrero")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("EstanciaId");

                    b.ToTable("CaptacionesGanado", (string)null);
                });

            modelBuilder.Entity("SIGA.Domain.Entities.DetalleLoteGanado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ActualizadoPor")
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadCabezas")
                        .HasColumnType("integer");

                    b.Property<Guid>("CaptacionGanadoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreadoPor")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FechaEstimadaFaena")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotasZootecnicas")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<double?>("PesoPromedioEstimadoKg")
                        .HasColumnType("double precision");

                    b.Property<string>("Raza")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SistemaAlimentacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CaptacionGanadoId");

                    b.ToTable("DetallesLoteGanado", (string)null);
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Dispositivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("IdentificadorDispositivo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("UbicacionActual")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UltimaSincronizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Dispositivos", (string)null);
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Estancia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaptadorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EstadoSync")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaCreacionLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaSincronizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("HectareasTotales")
                        .HasColumnType("double precision");

                    b.Property<double>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("ModificadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Municipio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Propietario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Renspa")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Representante")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CaptadorId");

                    b.ToTable("Estancias", (string)null);
                });

            modelBuilder.Entity("SIGA.Domain.Entities.LogAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Detalle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdRegistroAfectado")
                        .HasColumnType("uuid");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FechaHora");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogsAuditoria", (string)null);
                });

            modelBuilder.Entity("SIGA.Domain.Entities.MovimientoGanado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadCabezas")
                        .HasColumnType("integer");

                    b.Property<Guid>("CaptacionGanadoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("EstadoSync")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacionLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaSincronizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModificadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("TipoGanado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CaptacionGanadoId");

                    b.ToTable("MovimientosGanado", (string)null);
                });

            modelBuilder.Entity("SIGA.Domain.Entities.PermisoUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("TipoPermiso")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PermisosUsuario", (string)null);
                });

            modelBuilder.Entity("SIGA.Domain.Entities.RegistroAlimentacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaptacionGanadoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("EstadoSync")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacionLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaSincronizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModificadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<double?>("RacionBaseKgAnimal")
                        .HasColumnType("double precision");

                    b.Property<double?>("SuplementoProteicoKgAnimal")
                        .HasColumnType("double precision");

                    b.Property<string>("TipoAlimentacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CaptacionGanadoId");

                    b.ToTable("RegistrosAlimentacion", (string)null);
                });

            modelBuilder.Entity("SIGA.Domain.Entities.RegistroSanitario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaptacionGanadoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("EstadoSync")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacionLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaSincronizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModificadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ProductoTratamiento")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RegistradoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CaptacionGanadoId");

                    b.HasIndex("RegistradoPorUsuarioId");

                    b.ToTable("RegistrosSanitarios", (string)null);
                });

            modelBuilder.Entity("SIGA.Domain.Entities.SectorAsignado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NombreSector")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Zona")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SectoresAsignados", (string)null);
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cargo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasDiscriminator<string>("TipoUsuario").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Administrador", b =>
                {
                    b.HasBaseType("SIGA.Domain.Entities.Usuario");

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Captador", b =>
                {
                    b.HasBaseType("SIGA.Domain.Entities.Usuario");

                    b.HasDiscriminator().HasValue("Captador");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.CaptacionGanado", b =>
                {
                    b.HasOne("SIGA.Domain.Entities.Estancia", "Estancia")
                        .WithMany("Captaciones")
                        .HasForeignKey("EstanciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estancia");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.DetalleLoteGanado", b =>
                {
                    b.HasOne("SIGA.Domain.Entities.CaptacionGanado", "CaptacionGanado")
                        .WithMany("Detalles")
                        .HasForeignKey("CaptacionGanadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaptacionGanado");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Dispositivo", b =>
                {
                    b.HasOne("SIGA.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Dispositivos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Estancia", b =>
                {
                    b.HasOne("SIGA.Domain.Entities.Captador", "Captador")
                        .WithMany("Estancias")
                        .HasForeignKey("CaptadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Captador");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.LogAuditoria", b =>
                {
                    b.HasOne("SIGA.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.MovimientoGanado", b =>
                {
                    b.HasOne("SIGA.Domain.Entities.CaptacionGanado", "CaptacionGanado")
                        .WithMany("Movimientos")
                        .HasForeignKey("CaptacionGanadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaptacionGanado");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.PermisoUsuario", b =>
                {
                    b.HasOne("SIGA.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Permisos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.RegistroAlimentacion", b =>
                {
                    b.HasOne("SIGA.Domain.Entities.CaptacionGanado", "CaptacionGanado")
                        .WithMany("RegistrosAlimentacion")
                        .HasForeignKey("CaptacionGanadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaptacionGanado");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.RegistroSanitario", b =>
                {
                    b.HasOne("SIGA.Domain.Entities.CaptacionGanado", "CaptacionGanado")
                        .WithMany("RegistrosSanitarios")
                        .HasForeignKey("CaptacionGanadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGA.Domain.Entities.Usuario", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CaptacionGanado");

                    b.Navigation("RegistradoPor");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.SectorAsignado", b =>
                {
                    b.HasOne("SIGA.Domain.Entities.Usuario", "Usuario")
                        .WithMany("SectoresAsignados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.CaptacionGanado", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Movimientos");

                    b.Navigation("RegistrosAlimentacion");

                    b.Navigation("RegistrosSanitarios");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Estancia", b =>
                {
                    b.Navigation("Captaciones");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Dispositivos");

                    b.Navigation("Permisos");

                    b.Navigation("SectoresAsignados");
                });

            modelBuilder.Entity("SIGA.Domain.Entities.Captador", b =>
                {
                    b.Navigation("Estancias");
                });
#pragma warning restore 612, 618
        }
    }
}
